config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :customers
  root 'customers#index'
  resources :comments, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
  validates :customer_id, presence: true

  belongs_to :customer
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :customers
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :company
  has_many :comments

#validates :対象となるからむ
validates :family_name, presence: true, length: { maximum: 20}
validates :given_name, presence: true, length: { maximum: 20}
#正規表現
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true,
format: { with: VALID_EMAIL_REGEX }, uniqueness: true
validates :company_id, presence: true


  def full_name
    full_name = family_name + given_name + "様"
    #return full_name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

def full_name
    full_name = family_name + given_name + "様"
    #return full_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :family_name
    devise_parameter_sanitizer.for(:sign_up) << :given_name
    devise_parameter_sanitizer.for(:account_update) << :family_name
    devise_parameter_sanitizer.for(:account_update) << :given_name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to customer_url(@comment.customer_id)
    else
      redirect_to customer_url(@comment.customer_id)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    customer_id = @comment.customer_id
    @comment.destroy
    redirect_to customer_url(customer_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :customer_id)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :set_customer, only: [:show, :update , :edit, :destroy]

  before_action :set_company, only: [:new, :edit]

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @customers = Customer.page(params[:page])
  end

  def new
    #@companies = Company.all
    @customer = Customer.new #なぜ大文字にする？modelだから？
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      #trueの時
      redirect_to @customer #なぜこれでshowに行ける？
    else render :new
      #falseの時render :new
    end
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end
  end

  def show
    @customer = Customer.find(params[:id])
    @comments = @customer.comments
    @comment = Comment.new #(form_forで使う)
  end

  def destroy
    @customer.destroy
    redirect_to customers_url
  end

  private
  def customer_params　#新しく作ったらここが必要
    params.require(:customer).permit(
      :family_name,
      :given_name,
      :email,
      :company_id
      )
  end

  #befrore_acton置き場
  def set_customer
    @customer = Customer.find(params[:id])
  end

  def set_company
    @customer = Customer.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>

<% if @customer.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= @customer.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :family_name %>
    <%= f.text_field :family_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :given_name %>
    <%= f.text_field :given_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :company_id %>
    <%= f.collection_select :company_id, Company.all, :id, :name %>
  <%= f.submit %>
<% end %>

app/views/customers/edit.html.erb
<h1>顧客編集画面</h1>
<%= render partial: 'form' %>
<button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#delete-customer">顧客情報を削除する</button>
<div class="modal fade" id="delete-customer">
 <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title">顧客情報の削除</h4>
     </div>
     <div class="modal-body">
       <p><%= @customer.family_name %>さんを削除しますか？</p>
     </div>
     <div class="modal-footer">
       <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
       <%= link_to '削除する', @customer, method: :delete, class: "btn btn-danger" %>
     </div>
   </div>
 </div>
</div>

app/views/customers/index.html.erb
<h1>顧客情報一覧</h1>
<p>お客様情報が表示されます。</p>
<table class="table table-striped">
  <thead>
    <th>会社名</th>
    <th>姓</th>
    <th>名</th>
    <th>電子メール</th>
    <th>詳細</th>
    <th>編集</th>
    <th>削除</th>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.company.name %></td>
        <td><%= customer.family_name %></td>
        <td><%= customer.given_name %></td>
        <td><%= customer.email %></td>
        <td><%= link_to '詳細', customer, class: "btn btn-primary" %></td>
        <td><%= link_to '編集', edit_customer_path(customer), class: "btn btn-primary" %></td>
        <td><%= link_to '削除', customer, method: :delete,
        data: {confirm: "You sure?"}, class: "btn btn-primary" %></td>

      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @customers %>

app/views/customers/new.html.erb
<h1>顧客新規登録</h1>
<%= render partial: 'form' %>

app/views/customers/show.html.erb
<div class="row">
  <div class="col-md-12">
    <dl>
      <dt>名前</dt>
      <dd><%= @customer.full_name %></dd>
       <dt>電子メール</dt>
      <dd><%= @customer.email %></dd>
      <dt>会社名</dt>
      <dd><%= @customer.company_id %></dd>
    </dl>
  </div>
</div>

<hr />

<div class="row">
  <div class="col-lg-12">
  <% @comments.each do |comment| %>
      <p>
        <%= comment.body %>
      </p>
       <p class="text-muted">
    投稿日時：<%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
    <%= link_to "削除する", comment_path(comment), method: :delete %>
  </p>
    <% end %>
  <div class="col-lg-12">
    <%= form_for @comment do |f| %>
      <div class="form-group">
        <%= f.label :body , '対応内容' %><br>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <%= f.hidden_field :customer_id, value: @customer.id %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/customers">顧客管理システム</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
       <p class="navbar-text navbar-right"><%= current_user.full_name%>でログイン中</p>
     <% end %>
        <%# if 条件文　ユーザーがログインしているなら %>
        <% if user_signed_in? %>
            <li><%= link_to "更新", edit_user_registration_path %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
             <%# else条件文　ユーザーがログインしていないなら %>
          <% else %>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
<%= render partial: 'layouts/header' %>

<div class="container">
  <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>